### ISSUE TITLE
Null Ref if a Cell is null

### ISSUE THREAD

**Issue by mstum** [mstum/Simplexcel#25]
```cs
var ws = new Worksheet("Testing");

ws.Cells[0,0] = "Foo";
ws.Cells[1,1] = null;

var wb = new Workbook();
wb.Add(ws);
wb.Save(@"test.xlsx");
```

NullReferenceException:

```
at Simplexcel.XlsxInternal.XlsxWriter.XlsxWriterInternal.HandleLargeNumbers(Worksheet sheet)
at Simplexcel.XlsxInternal.XlsxWriter.XlsxWriterInternal.Save(Workbook workbook, Stream outputStream, Boolean compress)
at Simplexcel.XlsxInternal.XlsxWriter.Save(Workbook workbook, Stream outputStream, Boolean compress)
at Simplexcel.Workbook.Save(Stream stream, Boolean compress)
at Simplexcel.Workbook.Save(String filename, Boolean compress)
```

**Comment by mstum** [comment]
https://github.com/mstum/Simplexcel/issues/43
